### ISSUE TITLE
Find a suitable ASIC resistant hashing algo

### ISSUE THREAD

**Issue by alexdovzhanyn** [UltraDark/UltraDark#18]
Currently we're using SHA256 for the block hashes. While this is fine and secure, in the interest of leveling the playing field for miners, lets find a good ASIC-resistant hashing algorithm to use instead.

**Comment by Nijinsha** [comment]
Some of the altcoins achieve this by using algorithms that use a lot of memory. Most of the ASIC machines will not have high memory thus making the hashing algorithm ASIC resistant.

**Comment by alexdovzhanyn** [comment]
Would you like to self-assign this and try to find a few algorithms we might be able to use (keeping in mind that we'd prefer to use an elixir/erlang library)?

**Comment by Nijinsha** [comment]
Just a thought : Instead of using one algorithm, can't we change the algorithm for each block based on some criteria. No ASIC machine can be configured to work for multiple algorithm(But a CPU can, that is what makes it general purpose). So people with ASIC can mine a selected number of blocks but never makes mining centralized to only ASIC machines.

**Comment by alexdovzhanyn** [comment]
I think thats an interesting idea, but in practice it would br difficult to enforce, since consensus depends partially on nodes being able to identify which algorithm is used, and it would also make block time wildly unpredictable, since each algorithm has different speeds and efficiencies (plus each gpu has a different performance based on the algorithm thats used) so there wouldn't be much incentive for a miner if they can't predict roughly how likely they are to find the next hash

**Comment by Nijinsha** [comment]
https://steemit.com/cryptocurrency/@buggedout/asic-resistance-is-a-myth-dash-is-conquered
This article does a great analysis on ASIC resistant algorithms.

**Comment by Nijinsha** [comment]
Attaching a c library containing SHA3 and a lot of other algorithms. 
https://github.com/rhash/RHash
